### PR TITLE
Resubmit of PR5

### PR DESCRIPTION
**Pull request by KoenZomers**
Resubmit of PR #5

### CODE REVIEW

**Comment by AndreasHassing** [comment]
@KoenZomers: did you verify whether their API is case sensitive?

I used all-caps, as that is what the API itself is using.

**Comment by KoenZomers** [comment]
Thanks for keeping me crisp on that one @AndreasHassing. Just did a test and it's case sensitive indeed. I have updated the code to accommodate this. It also returns for me if I do use the capitalized version:

> {"errors":[{"code":"accessibleOnlyForSkillBasedApps","title":"operation 'lock home presence' is not supported for home xxxxxx (xxxxx@xxxxx.xx): home presence locking is available only for Skill-based app homes"}]}

Could it be that you're on Tado V3+ to make it work for you?

**Comment by AndreasHassing** [comment]
Did you configure Geofencing in the app @KoenZomers?

**Comment by KoenZomers** [comment]
> Did you configure Geofencing in the app @KoenZomers?

Yep, that's turned on, so that can't be it. You didn't purchase the upgrade to V3+ or bought a V3+ set from the start? I'm pretty sure it will be in that.

**Comment by AndreasHassing** [comment]
@KoenZomers not sure, but they're fairly new so I might be using V3+ (nothing in the app indicates version).

**Comment by KoenZomers** [comment]
Does the app show square tiles for each room or do you have to go to the hamburger menu on the top left to switch rooms? First is V3+, latter V3. I've got the latter.

**Comment by AndreasHassing** [comment]
I have V3+, then. I guess the set I bought came with that version 😊.

**Comment by AndreasHassing** [comment]
> Thanks for keeping me crisp on that one @AndreasHassing. Just did a test and it's case sensitive indeed. __I have updated the code to accommodate this.__ ...

I think you forgot to do __that__ 😎.

**Comment by KoenZomers** [comment]
True, wanted to stick with the coding style I typically apply and still use the mandatory uppercase casing towards Tado :)

Guess we finally have the reason why the forced away doesn't work for me, so I blindly depend on your testing for this ;)

**Pull request merged**
